### ISSUE TITLE
Increase tolerance for hidden tabs problem on linux

### ISSUE THREAD

**Issue by Codedotexe** [wingman-jr-addon/wingman_jr#191]
The hidden tabs problem still occurred for me on the latest version of the addon, I investigated it a bit more and found out that the highest difference I encountered in the `bkApproxEq` function for me was `0.0193` . So I increased the tolerance value from `0.01` to `0.02` and now it seems to work without any problems, although I don't know if this value will work for everyone.

Also I wanted to say I really appreciate the amount of effort you have put into this addon :)

**Comment by wingman-jr-addon** [comment]
Fixing in #192
