### ISSUE TITLE
Still some fonts show the � symbol

### ISSUE THREAD

**Issue by Dragodraki** [wingman-jr-addon/wingman_jr#196]
For exmaple here:
https://www.acronis.com/de-de/products/true-image/comparison/

Nothing big, but maybe you can update all possible fonts to allow special characters (it shouldn't mean any harm to only display alphabet characters no matter how weird they are)

**Comment by wingman-jr-addon** [comment]
Thanks @Dragodraki  - I took a look here to see what was going on. Basically, there is a `charset=` string but it is with `utf8` which is apparently an allowed alias for `utf-8` as per https://encoding.spec.whatwg.org/#names-and-labels . I'll need to some aliases and see if that works...

**Comment by wingman-jr-addon** [comment]
![image](https://github.com/wingman-jr-addon/wingman_jr/assets/55339824/681490e0-3d04-43fb-9c23-6dfc5352ace3)

**Comment by wingman-jr-addon** [comment]
Should be fixed by d8035027a0a4db5b4b73bb75cd513bc20ebbc8d2
Thanks @Dragodraki !
