### ISSUE TITLE
Icons on articles on dev.to do not load if Wingman Jr. is turned on

### ISSUE THREAD

**Issue by SufianBabri** [wingman-jr-addon/wingman_jr#203]
The screenshot below shows what I mean.

![Screenshot of an article on dev.to having the issue](https://github.com/wingman-jr-addon/wingman_jr/assets/9989266/678cadcf-7b22-4368-95ae-dfd21c7d846f)

Steps to reproduce:
1. Turn on the Wingman Jr. extension [Firefox 125.0.2 (64-bit), macOS]
2. Go to [this page](https://dev.to/dannyhw/apple-privacy-manifest-for-react-native-29fk)
3. If the icons show up, either wait till the page load completes or open the "Network" tab of the "Web Developer Tools" and check the "Disable Cache" and then reload the page

**Comment by wingman-jr-addon** [comment]
Thanks @SufianBabri ! I'm having a bit of trouble reproducing this. On Firefox 125.0.3 (64-bit) Windows I see it load when I visit the link directly:
![image](https://github.com/wingman-jr-addon/wingman_jr/assets/55339824/ba4031cd-b3d1-4784-902a-c1ad4d739ad0)

I tried the "Disable Cache" as well as you can see and didn't have an issue. Any thoughts?

**Comment by SufianBabri** [comment]
Strange. It works fine on my side too. I can't reproduce it with Firefox 125.0.3 on macOS either. Might have resolved after I rebooted my system or may even be fixed by restarting the browser.

**Comment by wingman-jr-addon** [comment]
Well thanks for looking into it @SufianBabri  and reporting a bug! I appreciate it.
