### ISSUE TITLE
Feature request: disable with a single click

### ISSUE THREAD

**Issue by stephen-farris-jhuapl-edu** [wingman-jr-addon/wingman_jr#66]
Could you add an option to disable Wingman with a single click, e.g. with a **Disabled** menu option above **Trusted**? I only use the software when searching stock photo sites for stock photos to use in presentations and the like, so I don't need to use Wingman most of the time. It would be great to be able to quickly turn it off so false positives don't cause problems when I don't need to use the tool, and turn it back on when I do. It's a great tool, and this would make it even better!

**Comment by wingman-jr-addon** [comment]
Hey @stephen-farris-jhuapl-edu I think that's a great feature request. The only thing I might want to balance it out against is the fact that I think some folks might use this for their kids, and I don't particularly want a nice easy button for the kids to click just by exploring the interface. Still, I know I've wanted this feature, too.
So how about this - what if I added a feature in settings labeled "Show on/off button" and then if that's turned on it'll show up in the menu. Great for those that know, while not very discoverable by kids. Sound reasonable?

**Comment by stephen-farris-jhuapl-edu** [comment]
That sounds like a great compromise!

**Comment by wingman-jr-addon** [comment]
Tinkering on this a bit over [here](https://github.com/wingman-jr-addon/wingman_jr/tree/on-off-switch). I hadn't done much with the UI part in this project yet and the need to do everything via RPC means it's bad and hacky right now. Debating if I want to put in a proper solution now or wait until thing number three comes along in the UI.

At any rate, I'm guessing the desired behavior would be to keep the model loaded and warmed up so it's fast to turn it back on. Going with that approach for now.

**Comment by wingman-jr-addon** [comment]
See #68

**Comment by wingman-jr-addon** [comment]
This is now out in release 1.2.0 @stephen-farris-jhuapl-edu - give it a try! It won't win any visual design awards but should do what you'd like.

**Comment by stephen-farris-jhuapl-edu** [comment]
It looks good, thanks!

**Comment by wingman-jr-addon** [comment]
Great! I like to hear how people actual end up using the plugin, so keep the feedback coming - I appreciate it. Thanks!
