### ISSUE TITLE
Version 1.2.1 breaks images in pages loaded from target="_blank" links

### ISSUE THREAD

**Issue by abdullahezzat1** [wingman-jr-addon/wingman_jr#72]
Try clicking a link that opens in a new tab. You'll see most images broken in that page.

My case was in vuejs.org. Just click any link from the ecosystem tab or the sponsors below.

I'm using Firefox 82 on Linux.

**Comment by wingman-jr-addon** [comment]
Hello @abdullahezzat1 and thanks for telling me about what you encountered!

I've tried to reproduce the same thing on my Windows computer here and I don't think I was seeing the same thing you were. I [recorded my screen for a bit](https://youtu.be/qT7P_H9rTDY) and clicked those links but I was still seeing the same images. I'm on Windows with Firefox 82.0.2 64bit.

Also, I'd like to double check that you were using the released version and not something on master. I had a change that broke top-level directly typed URL's [here](https://github.com/wingman-jr-addon/wingman_jr/commit/857ac85c9e94467d99283786842b1aa15f7fd00f) but I fixed it [here](https://github.com/wingman-jr-addon/wingman_jr/commit/3af5b5c0763c2fcbe7638b135708fd713a593c21) and it was not in a release.

If you are able, can you please confirm that [Release 1.2.0 (zip provided)](https://github.com/wingman-jr-addon/wingman_jr/releases/tag/release-1.2.0) does indeed work for you? Also, given the nature of the changes to 1.2.1, do you use an English version of Firefox or a different one? I'm wondering if there is some difference perhaps with that as well. And as a final check, do you have many other plugins going at the same time?

Thanks for your help!

**Comment by abdullahezzat1** [comment]
I tried again and everything is working fine! Didn't really know what the problem was, but it wasn't working before until I disable the extension. Thanks for responding.

**Comment by wingman-jr-addon** [comment]
No problem! I am going to close for now but if you see it again please let me know. Thank you for taking the time to check it again.
