### ISSUE TITLE
Firefox 83 Performance Unusable

### ISSUE THREAD

**Issue by wingman-jr-addon** [wingman-jr-addon/wingman_jr#75]
After Firefox upgraded from 82 to 83, performance became unusable due the WebGL context not loading. See [related blog post](https://wingman-jr.blogspot.com/2020/11/firefox-83-problem.html)
```
Failed to create WebGL context: failIfMajorPerformanceCaveat: Compositor is not hardware-accelerated. tfjs_2.3.0.js:17:836684
Failed to create WebGL context: failIfMajorPerformanceCaveat: Compositor is not hardware-accelerated. tfjs_2.3.0.js:17:836613
Failed to create WebGL context: failIfMajorPerformanceCaveat: Compositor is not hardware-accelerated. tfjs_2.3.0.js:17:836639
Initialization of backend webgl failed tfjs_2.3.0.js:17:138478
e@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:1007713
@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:1058532
Tg</e.initializeBackend@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:137992
t/<@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:135797
u@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:104674
s/i._invoke</<@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:104428
g/</t[e]@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:105031
Wm@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:109975
o@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:110181
Vm/</<@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:110241
Vm/<@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:110119
Tg</e.ready</<@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:136133
t.ready@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/tfjs_2.3.0.js:17:1077805
wingman_startup@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/background.js:29:14
@moz-extension://4c8f2829-6dc5-48b0-a905-62714fc34ed3/background.js:938:1
```

**Comment by wingman-jr-addon** [comment]
@abdullahezzat1 If you happen to see this on Linux, let me know!

**Comment by abdullahezzat1** [comment]
Linux doesn't exactly have auto updates, and I don't update frequently for stability, but chances are if there's a problem on Windows, it would also exist on Linux.

**Comment by wingman-jr-addon** [comment]
As a mitigation of this, I'm pulling in the new WASM backend from TF.js as a fallback. I had a bit of trouble initially until I figured out I needed to download the .wasm files from the CDN and place them in the same directory, but made sense. Will get this released as soon as possible. See #76

**Comment by wingman-jr-addon** [comment]
Release 1.3.0 has been released with this fix.

**Comment by abdullahezzat1** [comment]
The WASM backend is much faster on Firefox 82 :heart_eyes:

**Comment by wingman-jr-addon** [comment]
Thanks for letting me know! I hope this helps other people as well.

**Comment by wingman-jr-addon** [comment]
(For me, WASM is now usable but about 50% of the WebGL backend speed.)

**Comment by wingman-jr-addon** [comment]
Tried #79 to see if a TF.js upgrade would fix it; I had tried other versions. It did not.

**Comment by wingman-jr-addon** [comment]
I performed a bisection on Firefox using `mozregression` and [filed a bug with Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1679671).

**Comment by wingman-jr-addon** [comment]
I believe I have separated the processing from the background now and have a decent fix. Also opens the way for multiple processors should there be an advantage.

**Comment by wingman-jr-addon** [comment]
Release 2.0.0 should fix this.
